### ISSUE TITLE
Add examples with work post?

### ISSUE THREAD

**Issue by melroy89** [chriskohlhoff/talking-async#3]
What about showing some examples with the work class and `post()` method? Documented here: https://think-async.com/Asio/asio-1.28.0/doc/asio/overview/core/threads.html

And the differences between a `co_spawn` vs `post()`? Eg. a worker with threads and post() method can be very useful is specific use-cases.

I now read this tutorial: https://studiofreya.com/cpp/boost/c-boost-asio-introduction-tutorial/. And I think in my situation I might want to use this. 

But there is no such example in either this repository nor in your examples folder AFAIK: https://github.com/chriskohlhoff/asio/tree/master/asio/src/examples

**EDIT:** And the work class has been deprecated in favor of `executor_work_guard`, so it's even more important to create a good example.

**Comment by jhgorse** [comment]
Did you check the tests and examples in the main project? I believe most of the features like these have coverage.

**Comment by melroy89** [comment]
Ow you are right I found a `post` example here: https://github.com/chriskohlhoff/asio/blob/ed5db1b50136bace796062c1a6eab0df9a74f8fa/asio/src/examples/cpp14/parallel_group/parallel_sort.cpp#L41 and here https://github.com/chriskohlhoff/asio/blob/ed5db1b50136bace796062c1a6eab0df9a74f8fa/asio/src/examples/cpp11/chat/chat_client.cpp#L35

Furthermore, the examples are still using the deprecated work class.

**Comment by jhgorse** [comment]
So is it fair to say that `post` is the older style with work class and that `co_spawn` is _The Way_ for c++20 and on?

**Comment by melroy89** [comment]
> So is it fair to say that `post` is the older style with work class and that `co_spawn` is _The Way_ for c++20 and on?

No both are valid use cases and both have their place. 
Only the work class of io service is deprecated.

**Comment by jhgorse** [comment]
Though you are still lacking `post` implementation breadcrumbs without the
deprecated work class.

Here is a unit test example with co_await:
https://github.com/chriskohlhoff/asio/blob/ed5db1b50136bace796062c1a6eab0df9a74f8fa/asio/src/tests/unit/experimental/awaitable_operators.cpp#L57

The search feature of Github is becoming more useful for querying test code
instead of implementation. Here is a useful filter to peruse for `post`
related content.
https://github.com/search?q=repo%3Achriskohlhoff%2Fasio+post+NOT+path%3A%2F%5Easio%5C%2Finclude%5C%2F%2F+path%3A%2F%5Easio%5C%2Fsrc%5C%2Ftests%5C%2Funit%5C%2F%2F&type=code

Cheers,
Joe

**Comment by melroy89** [comment]
I also now implemented `post()` in my thread pool implementation within C++ (without using Boost, only Asio), see: https://github.com/melroy89/RamBam/blob/main/include/thread-pool.h#L27

It post "the work" to `io_context_`, I created a `enqueue()` template method that calls the `post()` method of Asio. During the constructor of my `ThreadPool` class I construct `work_guard_` variable of type: `asio::executor_work_guard<asio::io_context::executor_type>`, see:  https://github.com/melroy89/RamBam/blob/main/src/thread-pool.cc#L7

Within my `start` method of this ThreadPool class, I execute `io_context_.run()` since io context is combined this work guard, the run() call becomes a blocking call in each of my C++ threads, see: https://github.com/melroy89/RamBam/blob/main/src/thread-pool.cc#L38. After this my threads are waiting to handle data. Again once `post()` is called with the first parameter of io_context (so the same `io_context_` variable as I mentioned earlier) and the function as secondary parameter (and function arguments as 3rd parameter), this will distribute the load among the threads automatically. Thus `asio::io_context` will automatically take care of the work I push to it via the `post` method. My code is open-source and licensed under MIT, feel free to look into it and use it if you wish.

**Comment by jhgorse** [comment]
Based on what I am reading in the source
https://github.com/chriskohlhoff/asio/blob/ed5db1b50136bace796062c1a6eab0df9a74f8fa/asio/include/asio/io_context.hpp#L562

it seems you not on a deprecated methodology regarding `post()`. =)

Cheers,
Joe

**Comment by melroy89** [comment]
That is what I keep saying. I said that the work class is deprecated only.
